name: Build and Release WinForms App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore NuGet packages
      run: nuget restore FractionTraining.sln
    
    - name: Build project
      run: msbuild FractionTraining.sln /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Upload EXE directly
      uses: softprops/action-gh-release@v2
      with:
        files: FractionTraining\bin\Release\FractionTraining.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
